package eu.blky.helloworld.net.common;

import java.net.URI;
import java.security.KeyStore;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

import javax.net.ssl.HostnameVerifier;
import javax.net.ssl.SSLContext;
//import javax.net.ssl.HostnameVerifier;
//import javax.net.ssl.SSLContext;
//import javax.net.ssl.SSLSession;
import javax.ws.rs.client.Client;
 
import javax.ws.rs.client.Entity;
import javax.ws.rs.client.Invocation;
//import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Invocation.Builder;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.Configuration;
//import javax.ws.rs.client.WebTarget;
//import javax.ws.rs.core.Configuration;
import javax.ws.rs.core.Link;
import javax.ws.rs.core.UriBuilder;

import org.glassfish.jersey.client.ClientConfig;

public class Initer implements  Client{
	
	private void callDebugger() {
		 
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:53:07 PM ;)!");
			 
			/*return*/  
	}
	//java.lang.NoClassDefFoundError: javax/net/ssl/HostnameVerifier
//	static HostnameVerifier v = null;
//	static SSLContext s = null;
	static Client c = null;
 
	static ClientConfig cc = null;
	private Initer() {}
	public static long getInited() {
		return inited;
	}
 
	static{
//		v = null;
//		s = null;
		System.out.println(javax.ws.rs.client.Client.class);
		 
		System.out.println(ClientConfig.class);
	}
	private static long inited = System.currentTimeMillis();
//	@Override
//	public boolean verify(String hostname, SSLSession session) {
//		 
//		// TODO Auto-generated method stub
//			if (1 == 1) 
//				throw new RuntimeException(
//							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:39:52 PM ;)!");
//			 
//			/*return*/ return false; 
//	}
	@Override
	public void close() {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:53:02 PM ;)!");
			 
			/*return*/  
	}

	@Override
	public Configuration getConfiguration() {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:54:43 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public Client property(String arg0, Object arg1) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:54:43 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public Client register(Class<?> arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:54:43 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public Client register(Object arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:54:43 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public Client register(Class<?> arg0, int arg1) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:54:43 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public Client register(Class<?> arg0, Class<?>... arg1) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:54:43 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public Client register(Class<?> arg0, Map<Class<?>, Integer> arg1) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:54:43 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public Client register(Object arg0, int arg1) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:54:43 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public Client register(Object arg0, Class<?>... arg1) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:54:43 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public Client register(Object arg0, Map<Class<?>, Integer> arg1) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:54:43 PM ;)!");
			 
			/*return*/ return null; 
	}
//	@Override
//	public HostnameVerifier getHostnameVerifier() {
//		callDebugger();
//		// TODO Auto-generated method stub
//			if (1 == 1) 
//				throw new RuntimeException(
//							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:54:43 PM ;)!");
//			 
//			/*return*/ return null; 
//	}
//	@Override
//	public SSLContext getSslContext() {
//		callDebugger();
//		// TODO Auto-generated method stub
//			if (1 == 1) 
//				throw new RuntimeException(
//							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:54:43 PM ;)!");
//			 
//			/*return*/ return null; 
//	}
	@Override
	public Builder invocation(Link arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:54:43 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public WebTarget target(String arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:54:43 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public WebTarget target(URI arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:54:43 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public WebTarget target(UriBuilder arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:54:43 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public WebTarget target(Link arg0) {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:54:43 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public HostnameVerifier getHostnameVerifier() {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:56:38 PM ;)!");
			 
			/*return*/ return null; 
	}
	@Override
	public SSLContext getSslContext() {
		callDebugger();
		// TODO Auto-generated method stub
			if (1 == 1) 
				throw new RuntimeException(
							"autogenerated from i1 return not checked value since Jan 17, 2019, 3:56:38 PM ;)!");
			 
			/*return*/ return null; 
	}
	 
 
	
}